__Copy__: Which copies an array into another variable.

There are three type of copies:

1.Normal copy.

2.shallow copy.

3.base copy.

In [8]:
#example for normal copy.
import numpy as np
a = np.arange(1, 13)
print(a)
b = a
print(b)
print(a.shape)
print(b.shape)
b.shape = 2, 3, 2
print(b)
print(b.shape)
print(a.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
(12,)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
(2, 3, 2)


__Note__: This copies entire data present 'a' into 'b', thus the address of both the variables remain same.

This copy affect the original data.

__Note1__: If you alter the dimension of an array usinh the reshape method then original data doesn't get affected.

In [11]:
#example for shallow copy.
import numpy as np
a = np.arange(1, 13)
b = a.view()
print(a)
print(b)
b is a

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


False

__Note__: View function is just like visualizing the and keeping that data in memory and returning it back.

__Note1__: This copy will also affect the original data.

In [14]:
import numpy as np
a = np.arange(12)
b = a.view()
print(a)
print(b)
b[0] = 10
b[1] = 3
print(a)
print(b)
print(a is b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[10  3  2  3  4  5  6  7  8  9 10 11]
[10  3  2  3  4  5  6  7  8  9 10 11]
False


In [15]:
#example demonstrating the base method.
import numpy as np
a = np.arange(3)
b = np.arange(3)
b.base is a

False

__Note__: In the above example 'a' and 'b' are two separate arrays, base method works if 'b' inherits all the elements from 'a'.

In [16]:
#example demonstrating the above note.
import numpy as np
a = np.arange(3)
c = a.view()
c.base is a

True

In [20]:
#example for copying a numpy array using copy function.
import numpy as np
a = np.arange(1, 13)
b = a.copy()
print(a)
print(b)
b[0] = 99
print(b)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[99  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


__Note__: Above example demonstrates that copy function doesn't affect the original data.

In [23]:
#example demonstrating zeros_like function.
import numpy as np
a = np.arange(1, 13).reshape(3, 4)
b = np.zeros_like(a)
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


__Note__: This function will print the number of zeros specified in reshape parenthesis.

In [25]:
#example demonstrating ones_like function.
import numpy as np
a = np.arange(1, 5).reshape(2, 2)
b = np.ones_like(a)
print(a)
print(b)

[[1 2]
 [3 4]]
[[1 1]
 [1 1]]


__Note__: This function will print the number of ones specified in reshape parenthesis.

In [30]:
#example demonstrating ones_like function.
import numpy as np
a = np.arange(10).reshape(2, 5)
b = np.empty_like(a)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
