__Shape Manipulation__: Is nothing but changing the shape or dimension of an array.

In [1]:
#1.reshape().
import numpy as np
a = np.arange(1, 13).reshape(4, 3)
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


__Note__: Above function does not affect the original array. And this function also converts single array vector to multidimensional array.

In [5]:
#2.resize().
import numpy as np
a = np.arange(12)
a.resize(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


__Note__: Vector 'a' gets converted to multi-dimensional array. And original array gets modified.

__Review__:

reshape(): Is used to change the structure of data from 1D to ND where N is (2, 3, 4, ...) without affecting the original array.

resize(): Is used to change the structure of data from 1D to ND where N is (2, 3, 4, ...) and will affect the original array.

ravel(): Used to change the structure of data from ND to 1D. And this function affects the original data.

In [2]:
#3.ravel():example for ravel function.
import numpy as np
a = np.arange(1, 13).reshape(3, 4)
b = a.ravel()
print(b)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
#few important examples for reshape, resize and ravel.
import numpy as np
a = np.arange(1, 13)
b = a.reshape(4, 3)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
import numpy as np
a = np.arange(1, 13)
a.resize(3, 4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
import numpy as np
a = np.arange(1, 13).reshape(3, 4)
np.ravel(a)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
import numpy as np
a = np.floor(10*np.random.random(10))
print(a)
print(a.shape)
print(a.ravel())
print(a.reshape(2, 5))
print(a.resize(5, 2))

[2. 6. 0. 7. 7. 4. 4. 4. 3. 6.]
(10,)
[2. 6. 0. 7. 7. 4. 4. 4. 3. 6.]
[[2. 6. 0. 7. 7.]
 [4. 4. 4. 3. 6.]]
None


In [17]:
#4.flatten()-This function is also used to convert Multidimensional array to 1D(same as ravel function but will not affect the original data).
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(a.flatten())
print(a)

[1 2 3 4]
[[1 2]
 [3 4]]


Note: 'C' argument specified inside the paranthesis refer rowise flattening.

'F' argument specified inside the paranthesis refer to columnwise flattening.

Whereas default argument is 'C'

In [20]:
#example demonstrating the above note.
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(a.flatten('C'))
print(a.flatten('A'))
print(a.flatten('K'))
print(a.flatten('F'))
print(a)

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 3 2 4]
[[1 2]
 [3 4]]
