__Split__: This will split the array.
    
There are 5 types:

1.Vertical split.

2.Horizonal split.

3.Depth_split.

4.array_split.

5.split.

In [13]:
import numpy as np
a = np.arange(1, 10).reshape(3, 3)
print(a)
b = np.vsplit(a, 3)
print(b)
c = np.arange(1, 17).reshape(4, 4)
print(c)
d = np.vsplit(c, 2)
print(d)
e = np.vsplit(c, np.array([3]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


In [15]:
#example for horizontal split.
import numpy as np
a = np.arange(16).reshape(4, 4)
print(a)
b = np.hsplit(a, 2)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [3]:
#example for dsplit.
import numpy as np
a = np.arange(36).reshape(3, 3, 2, 2)
print(a)
b = np.dsplit(a, 2)
print(b)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]


 [[[24 25]
   [26 27]]

  [[28 29]
   [30 31]]

  [[32 33]
   [34 35]]]]
[array([[[[ 0,  1]],

        [[ 4,  5]],

        [[ 8,  9]]],


       [[[12, 13]],

        [[16, 17]],

        [[20, 21]]],


       [[[24, 25]],

        [[28, 29]],

        [[32, 33]]]]), array([[[[ 2,  3]],

        [[ 6,  7]],

        [[10, 11]]],


       [[[14, 15]],

        [[18, 19]],

        [[22, 23]]],


       [[[26, 27]],

        [[30, 31]],

        [[34, 35]]]])]


In [4]:
#example for array split
import numpy as np
a = np.arange(26)
b = np.array_split(a, 2)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25]
[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])]


In [5]:
#example for split.
import numpy as np
a = np.arange(16)
b = np.split(a, 4)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11]), array([12, 13, 14, 15])]
