__Stack__: Is nothing but combining the arrays.

There are 4 types of stacks:

1.Vertical stack.

2.Horizontal stack.

3.Column stack.

4.Depth stack.

In [5]:
#examples for vertical stack.
import numpy as np
a = np.floor(10*np.random.random(4)).reshape(2, 2)
b = np.floor(10*np.random.random(4)).reshape(2, 2)
print(a)
print(b)
c = np.vstack((a, b))
print(c)

[[2. 9.]
 [5. 0.]]
[[2. 7.]
 [0. 2.]]
[[2. 9.]
 [5. 0.]
 [2. 7.]
 [0. 2.]]


In [6]:
#examples for horizontal stack.
import numpy as np
a = np.floor(10*np.random.random(4)).reshape(2, 2)
b = np.floor(10*np.random.random(4)).reshape(2, 2)
print(a)
print(b)
c = np.hstack((a, b))
print(c)

[[8. 8.]
 [8. 9.]]
[[6. 2.]
 [4. 3.]]
[[8. 8. 6. 2.]
 [8. 9. 4. 3.]]


In [8]:
#example for column stack.
import numpy as np
from numpy import newaxis
a = np.arange(1, 5).reshape(2, 2)
print(a)
b = np.column_stack(a)
print(b)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


__Note__: Column_stack is just like array transpose.(There is no row_stack)

column_stack()- Is used to convert 1D to multi-dimension.

In [11]:
#newaxis:1D to 2D
import numpy as np
from numpy import newaxis
a = np.array([4,2])
b = a[:, newaxis]
c = a[newaxis, :]
print(a)
print(b)
print(c)

[4 2]
[[4]
 [2]]
[[4 2]]


In [14]:
#newaxis: 2D to 3D
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(a)
b = a[:, newaxis]
print(b)
c = a[newaxis, :]
print(c)

[[1 2]
 [3 4]]
[[[1 2]]

 [[3 4]]]
[[[1 2]
  [3 4]]]


In [19]:
import numpy as np
from numpy import newaxis
a = np.array([[1], [2], [3]])
print(a)
b = a[newaxis, :]
print(b)
c = a[:, newaxis]
print(c)

[[1]
 [2]
 [3]]
[[[1]
  [2]
  [3]]]
[[[1]]

 [[2]]

 [[3]]]


In [23]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
b = a[:, newaxis]
print(b)
c = a[newaxis, :]
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


__Note__: This function is used to add an axis whereever it is mentioned.

In [26]:
#example for depth stack.
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.dstack((a, b))
print(a)
print(b)
print(c)

[1 2 3]
[4 5 6]
[[[1 4]
  [2 5]
  [3 6]]]


__Note__: This function is used to convert rows into columns.

In [27]:
#example for r_
import numpy as np
a = np.r_[1:5, 5, 6]
print(a)

[1 2 3 4 5 6]


In [28]:
#example for c_
import numpy as np
a = np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]
print(a)

[[1 4]
 [2 5]
 [3 6]]


In [29]:
import numpy as np
a = np.c_[np.array([[1, 2, 3]]), np.array([[4, 5, 6]])]
print(a)

[[1 2 3 4 5 6]]
